### ISSUE TITLE
The Excel document scoring has not been updated for the new content 

### ISSUE THREAD

**Issue by newtonsgroove** [w3c/maturity-model#192] opened 2023-09-25 22:07 UTC
Here is the content reformatted for a GitHub issue:

# The Excel document scoring has not been updated for the new content (if indeed the new content is to be there. It is possible to score well beyond 100% by populating categories.

## To reproduce

1. Open Excel doc
2. Select a tab (ex: 3.2. Knowledge and Skills) 
3. Change each status under “Optimize Stage Goal” to “Complete”
4. View result (I got as high as 325% NOTE: on 3.3 Support results of the same process resulted in 0%)

![325 percent](https://github.com/w3c/maturity-model/assets/5579431/4a368b66-ddca-41a2-8ca6-78633c010416)

**Comment by newtonsgroove** [comment] 2023-09-25 22:08
![325 percent](https://github.com/w3c/maturity-model/assets/5579431/004bcea1-5e76-434b-bb23-371f2afd0f8d)

**Comment by clapierre** [comment] 2023-10-06 14:15
Hello @newtonsgroove the reason why you are getting a % score above 100% is that you haven't filled in the statuses for the preceding stages.

Ideally the spreadsheet wouldn't allow us to add any status in a later stage until you mark the previous stage as "complete" but this is a lot of extra error checking/coding in the excel spreadsheet and this is only a stop-gap solution until we finalize all the dimensions / proof points at which time a more robust web implementation will be created. 

To fix your issue make all previous stages as complete and I believe you will get a more accurate % for your final score.

There was one issue that was fixed around the time you posted this issue in the Communication Tab on Cell C63 which didn't take into account the first 3 proof points in the total points available. Should have started at B11 not B14.  This has been fixed in the most recent version of the spreadsheet.

Thanks

**Comment by newtonsgroove** [comment] 2023-10-06 17:38
Thanx, Charles.  Is the following the correct methodology for the scoring?

Scoring Formulas Scoring Formula (Unweighted) Scoring Formula (Weighted)
Total Points Recieved ((Total Launch * 1) + (Total Integrate * 2) + (Total
Optimize * 3) ((Total Launch * 1) + (Total Integrate * 2) + (Total Optimize
* 3)
Total Points Available (Total Number of Proof Points - Proof Points Not
Applicable) (Total Number of Proof Points - Proof Points Not Applicable) * 3
Maturity Score (Dimension) Total Points Received / Total Points Available Total
Points Received / Total Points Available
Maturity Score (All Dimensions) Average of all Matutiry Scores (from seven
dimensions - unweighted)


Average of all Matutiry Scores (from seven dimensions - weighted)




*Dr.  Keith Newton *(Call me "Dr. Keith")
Executive Leader and Strategic a11y in Digital Accessibility Experience
614-654-4116 <%28614%29%20654-4116> |
https://www.linkedin.com/in/dr-keith-newton  | ***@***.***

**Comment by newtonsgroove** [comment] 2023-10-06 17:39
sorry,  I forgot:

Weights and Values
Maturity Stage Points (Unweighted) Points (Weighted)
Inactive 0 0
Launch 1 1
Integrate 1 2
Optimize 1 3
Not Applicable 0 0
Yet to be Added 0 0

*Dr.  Keith Newton *(Call me "Dr. Keith")
Executive Leader and Strategic a11y in Digital Accessibility Experience
614-654-4116 <%28614%29%20654-4116> |
https://www.linkedin.com/in/dr-keith-newton  | ***@***.***

**Comment by Helixopp** [comment] 2024-07-28 06:04
@newtonsgroove is this issue still resent? Or can we close this issue as resolved by the June updated draft?

**Comment by jeffkline** [comment] 2024-07-31 17:29
Waiting Response from originator

**Comment by Helixopp** [comment] 2024-07-31 17:34
Dr. Keith permitted us to close his spreadsheet issues with a comment that we will revisit once the document narrative nears final completion

**Closed by Helixopp** 2024-07-31 17:34 UTC

**Comment by jeffkline** [comment] 2024-07-31 17:48
Do you want me to go ahead and close it? Looks like it’s assigned to me.On Jul 31, 2024, at 12:35 PM, David Fazio ***@***.***> wrote:﻿
Dr. Keith permitted us to close his spreadsheet issues with a comment that we will revisit once the document narrative nears final completion

**Comment by Helixopp** [comment] 2024-07-31 17:50
I closed it already. But thx

**Comment by jeffkline** [comment] 2024-08-05 17:35
Subject: Texas Dept. of Information Resources) plan to review / use latest version of the Maturity Model.



Regards,


[A picture containing text, black, clock  Description automatically generated]<http://strategicaccessibility.com/>
 ***@***.***
 5  1  2   .   4  2  6   .   9   7  7  9

**Comment by jeffkline** [comment] 2024-10-30 03:32
Likely regrets for today. Traveling….On Oct 30, 2024, at 3:57 AM, David Fazio (W3C Calendar) ***@***.***> wrote:﻿





View this event in your browser






                Maturity Model TF Weekly Teleconference
                                Upcoming Confirmed


                                                                30 October 2024, 11:00
                -11:55                EST5EDT
            

                    Event is recurring weekly on Wednesday, starting from 2024-06-05, until 2027-01-01
                

                        Maturity Model Task Force
                    
 
Agenda
Agenda+ New Business
Agenda+ Update on Use Cases
Update on Github Issue #148 Resolution
Agenda+ Update on Github Issue #226 Resolution
Agenda+  Github Issue #230 Proof Points Communication Tab (Excel) Duplication
Agenda+ Github Issue #231 Excel Workbook - Duplicate Proofpoint
Agebda+ Github Issue #126 Update / NEWEST DLC Spreadsheet - Step 2
 
Joining Instructions


                                Join the meeting
                            
Zoom Meeting ID: 889 7090 8463
Passcode: 341074
Chat
irc.w3.org #maturity
 
Participants
Groups

Maturity Model Task Force
                                (View
                                    Calendar)
                            


        Report feedback and issues on
         GitHub.
                    
            To stop receiving these emails please update
            your calendar preferences.
